apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-deployment
    spec:
      containers:
      - name: helloworld-deployment
        image: public.ecr.aws/u4v6w6t7/test-ecr-repository:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        